name: Docker Image

on: [push]

env:
  IMAGE: "chavs1997/weatherboard"
  IMAGE_TAG: ""
  GOOGLECLOUD_PROJECT: ${{ secrets.GOOGLECLOUD_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GOOGLECLOUD_PROJECT }}
          service_account_key: ${{ secrets.GOOGLECLOUD_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: "Authenticate Docker"
        run: gcloud auth configure-docker

      # Calculate the image name
      - name: Calculate Docker image name
        run: echo "IMAGE_TAG=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build
        run: |
          docker build -t gcr.io/"$GOOGLECLOUD_PROJECT"/"$IMAGE":"$IMAGE_TAG" server

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-west1-docker.pkg.dev
          docker push gcr.io/$GOOGLECLOUD_PROJECT/$IMAGE:$IMAGE_TAG

      # Deploy to Google Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy weatherboard-and-zmanim --quiet --image gcr.io/$GOOGLECLOUD_PROJECT/$IMAGE:$IMAGE_TAG --region us-west1 --project $GOOGLECLOUD_PROJECT
